// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var generateSitemaps;
  generateSitemaps = require('./generator').generateSitemaps;
  generateSitemaps(function () {
    return console.log('generate done');
  });
}.call(this);
