// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cfr, config, env, err, extend, fs, path;
  cfr = require('coffee-script-redux/register');
  fs = require('fs');
  path = require('path');
  extend = require('underscore').extend;
  env = process.env.NODE_ENV || 'development';
  config = {};
  try {
    config = require('./' + env);
  } catch (e$) {
    err = e$;
    config = require('./defaults');
  }
  config.env = env;
  config.addAppSpecific = function () {
    var appConfig, appConfigPath;
    appConfigPath = path.join(process.cwd(), 'config', env);
    try {
      appConfig = require(appConfigPath);
    } catch (e$1) {
      err = e$1;
      console.log('WARN: Could not require app specific config ' + appConfigPath + ': ' + err);
    }
    if (null != appConfig)
      return extend(config, appConfig);
  };
  module.exports = config;
}.call(this);
